# Practice Set Of Numpy

Q.No.1- Write a Statement to Import Numpy

In [2]:
import numpy as nmp

Q.No.2- Create an array using Numpy.

In [3]:
np.array([2,4,5,6])

array([2, 4, 5, 6])

Q.No.3-Create an array of 10 random integer

In [5]:
a=np.random.randint(1,50,10)
print(a)

[48 30 12 32  6 46 22 25 21 29]


Q.No.4- Create an array which contain array 5, 10 times

In [6]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Q.No.5-Create a one dimensional array and convert that into 3X3 matrix.

In [7]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q.No.6-Create an array and then convert all the even number with zero.

In [10]:
a=np.arange(1,15)

a

In [16]:

a[a%2==0]=0
print(a)


[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]


Q.No.7- Create a 2D array of size 3*3 but all the elements shoulb be between 0 and 1

In [17]:
a=np.random.rand(3,3)
a

array([[0.902331  , 0.29987976, 0.61112889],
       [0.91351874, 0.98648048, 0.23261621],
       [0.60740154, 0.95571493, 0.29550787]])

Q.No.8- Peform the following slicing.

In [18]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

Q.No-9-Concatenate 2d array horizontally and vertically.

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Q.No.10-Create an element from 10 to 20

In [27]:
a=np.arange(10,21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#Student of Data Science
#Student of DataTrained
#Date-22-July-2022
#Time-8:40