In [ ]:
#Practice set of Numpy

In [1]:
import numpy as np

1) print the version number and configuration.

In [2]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

2) How to swap two columns in a numpy array?

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[:,[1,0,2]]

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

3) How to swap two rows in a an array?

In [14]:
a=np.arange((6)).reshape(2,3)

In [15]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a[[1,0],:]

array([[3, 4, 5],
       [0, 1, 2]])

4) How to reverse the columns of a an array?

In [22]:
a=np.arange(9).reshape(3,3)

In [23]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

5) How to create a boolean array?

In [27]:
a=np.full((3,3),True,dtype=bool)

In [29]:
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

6) How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr

In [30]:
a=np.arange((9)).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
a=a[a%2==1]
print(a)

[1 3 5 7]


7) How to replace items that satisfy a condition with another value in numpy array?

#Replace all odd numbers in arr with -1

In [33]:
a=np.arange((9)).reshape(3,3)
print(a)
a[a%2==1]=-1
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]


8) How to reshape an array?

Hint: Convert a 1D array to a 2D array with 2 rows

In [34]:
a=np.arange((9))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9) How to replace items that satisfy a condition without affecting the original array?

Hint: Replace all odd numbers in arr with -1 without changing arr

In [42]:
a=np.arange((9))
a
np.where((a%2==1),-1,a)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

10) Create a 4X2 integer array and Prints its attributes

In [44]:
a=np.arange((8)).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [45]:
a.size

8

In [47]:
a.ndim

2

In [48]:
a.shape

(4, 2)

In [49]:
type(a)

numpy.ndarray

In [55]:
a.dtype

dtype('int32')

11) How to extract all numbers between a given range from a numpy array? Hint: Get all items between 15 and 22 from array


In [56]:
a=np.arange((25))

In [57]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
np.where((a>=15)&(a<=22))

(array([15, 16, 17, 18, 19, 20, 21, 22], dtype=int64),)

In [59]:
a[(a>=15)&(a<=22)]

array([15, 16, 17, 18, 19, 20, 21, 22])

12) Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [66]:
a=np.arange(100,200,10).reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

13)How to get the positions where elements of two arrays match?

In [70]:
a=np.array([15,36,45,15,36,15,36,45])
b=np.array([36,15,45,65,36,78,65,45])

np.where((a==b))

(array([2, 4, 7], dtype=int64),)

 14) Return array of odd rows and even columns from given array: ([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [73]:
a=np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [74]:
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [77]:
a[::2,0::2]

array([[ 3,  9],
       [27, 33],
       [51, 57]])

15) How to stack two arrays vertically?

In [78]:
a=np.array([10,17,15,36,45,12,32])
b=np.array([32,45,65,78,98,12,32])


In [79]:
a

array([10, 17, 15, 36, 45, 12, 32])

In [80]:
b

array([32, 45, 65, 78, 98, 12, 32])

In [81]:
np.vstack((a,b))

array([[10, 17, 15, 36, 45, 12, 32],
       [32, 45, 65, 78, 98, 12, 32]])

16) How to stack two arrays horizontally?

In [82]:
a=np.array([10,17,15,36,45,12,32])
b=np.array([32,45,65,78,98,12,32])


In [83]:
a

array([10, 17, 15, 36, 45, 12, 32])

In [84]:
b

array([32, 45, 65, 78, 98, 12, 32])

In [85]:
np.hstack((a,b))

array([10, 17, 15, 36, 45, 12, 32, 32, 45, 65, 78, 98, 12, 32])

17) Create a null vector of size 10 but the fifth value which is 1

In [95]:
a=np.zeros((10),dtype=int)

In [99]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
a[4]=1

In [103]:
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

18) Create a 10x10 array with random values and find the minimum and maximum values

In [174]:
a=np.random.randint(100,500,10)

In [175]:
a

array([315, 230, 356, 225, 311, 429, 216, 437, 364, 450])

In [177]:
print(max(a))

450


In [112]:
print(min(a))

120


#19) Create a random vector of size 15 and find the mean value

In [114]:
a=np.random.randint(100,500,15)

In [115]:
a

array([238, 409, 178, 493, 403, 127, 346, 278, 131, 159, 481, 363, 425,
       207, 206])

In [117]:
print(a.mean())

296.26666666666665


20)Create a 2d array with 1 on the border and 0 inside

In [137]:
a=np.ones((5,5))

In [138]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [141]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

21) Is np.nan == np.nan

In [145]:
np.nan==np.nan

False

22) How to compute the mean, median, standard deviation of a numpy array?

In [146]:
a=np.array([10,50,20])

In [154]:
print(np.mean(a))

26.666666666666668


In [153]:
print(np.std(a))

16.996731711975947


In [152]:
print(np.median(a))

20.0


25) How to normalize an array so the values range exactly between 0 and 1?

In [4]:
import numpy as np

In [5]:
a=np.random.rand(5,5)

In [6]:
a

array([[0.23604812, 0.55324697, 0.83244493, 0.75140322, 0.12999136],
       [0.54020722, 0.76620111, 0.04108048, 0.94431394, 0.40736411],
       [0.24750105, 0.77811889, 0.01888922, 0.06002347, 0.73127796],
       [0.29203378, 0.5425403 , 0.14798019, 0.05279105, 0.81104613],
       [0.69126023, 0.77122615, 0.04067598, 0.65110655, 0.2020128 ]])

26) How to find the maximum value in each row of a numpy array 2d?

In [23]:
b=np.random.randint(100,500,25).reshape(5,5)

In [24]:
b

array([[394, 487, 150, 176, 126],
       [328, 232, 412, 199, 256],
       [218, 324, 491, 352, 130],
       [338, 240, 321, 494, 349],
       [466, 174, 413, 135, 160]])

In [27]:
np.amax(b,axis=1)

array([487, 412, 491, 494, 466])

37) You are given a 1-D array. Print the floor and ceil of all the elements of Array

In [36]:
a=np.array([1.2,1.6,1.6,1.9,1.11,1.5,1.7])

In [37]:
a

array([1.2 , 1.6 , 1.6 , 1.9 , 1.11, 1.5 , 1.7 ])

In [38]:
print(np.ceil(a))

[2. 2. 2. 2. 2. 2. 2.]


In [39]:
print(np.floor(a))

[1. 1. 1. 1. 1. 1. 1.]


39) There is N*M Matrix. Print the transpose and flatten results

In [42]:
a=np.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

42) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [69]:
a=np.array([[4,5,6],[1,2,3]])

In [70]:
a

array([[4, 5, 6],
       [1, 2, 3]])

In [71]:
np.sort(a,axis=1)

array([[4, 5, 6],
       [1, 2, 3]])

In [72]:
np.sort(a,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.sort(a,axis=None)

array([1, 2, 3, 4, 5, 6])

45) Make an array immutable (read-only)

In [86]:
b=np.zeros((10))

In [87]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
b[0]=1

In [90]:
b

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
b
b.flags.writeable=False

In [96]:
b

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
#46) How to sum a small array faster than np.sum?

In [99]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [100]:
np.sum(a)

6

In [105]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [107]:
np.add.reduce(a)

4950

47) Extract the integer part of a random array of positive numbers Z = np.random.uniform(0,10,10)

In [108]:
z=np.random.uniform(0,10,10)

In [109]:
z

array([3.15452512, 5.51041362, 2.79969747, 1.61273462, 3.58762895,
       2.84227013, 8.86080156, 8.38602155, 7.19162411, 9.13371426])

In [110]:
print(z//2)

[1. 2. 1. 0. 1. 1. 4. 4. 3. 4.]


In [111]:
#What is Random.shuffle

In [114]:
a=np.array([4,5,6,7,8,9,1,2,3])
a

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [118]:
np.random.shuffle(a)

In [119]:
a

array([5, 8, 3, 6, 4, 9, 2, 1, 7])

In [120]:
#Update Matrix=

In [121]:
a=np.arange(1,10).reshape(3,3)

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
a[0,1]=35

In [130]:
a

array([[11, 35, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [131]:
a[1,1]=45

In [132]:
a

array([[11, 35, 11],
       [ 4, 45,  6],
       [ 7,  8,  9]])

In [135]:
a[2,1]=55

In [136]:
a

array([[11, 35, 55],
       [ 4, 45,  6],
       [ 7, 55,  9]])

In [139]:
a[a>30]

array([35, 55, 45, 55])

In [140]:
np.where(a==55)

(array([0, 2], dtype=int64), array([2, 1], dtype=int64))

In [145]:
#Universal Function

In [147]:
a=np.array([[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[3,6,9]])



In [148]:
print("The Division of A and B is ",a/b)

The Division of A and B is  [[4.         2.5        2.        ]
 [2.33333333 1.33333333 1.        ]]


In [150]:
print('Lenear Cobination of A and B is',3*a-2*b)

Lenear Cobination of A and B is [[10 11 12]
 [15 12  9]]


In [151]:
#BroadCasting

In [153]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [164]:
a=np.array([[1,2,3]])

In [165]:

b=z+a

In [166]:
b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [167]:
c=a.T

In [168]:
c

array([[1],
       [2],
       [3]])

In [169]:
f=c+z

In [170]:
f

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [171]:
#Create an ndarray which is 4X1 to broadcast across columns

In [174]:
ad_cols=np.array([[0,2,2,3]])
ad_cols=ad_cols.T
print(ad_cols)

[[0]
 [2]
 [2]
 [3]]


In [ ]:
#Student of Data Science
#Studen of Data Trained
#Date-23-07-2022
#Time-12:01