In [59]:
#Numpy Ecercise

 Import numpy and see the version 

In [1]:
import numpy as np

In [5]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shriv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shriv/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

Create a 1d array of numbers from 0 to 9

In [9]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

create a 3X3 numpy array of all True's

In [19]:
s=np.full((3,3),True,dtype=bool)

In [20]:
s

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from array 

In [23]:
a=np.arange(11)
a=a[a%2==1]
a

array([1, 3, 5, 7, 9])

Replace all odd numbers with -1

In [24]:
a=np.arange(11)
a[a%2==1]=-1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


Replace all odd number in a with -1 without changing a

In [30]:
arr=np.arange(11)

In [31]:
np.where(arr%2==1,-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

How to stack array a and b vertically

In [35]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([9,8,7,6,5,4,3,2,1,])
print(b)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [41]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

How to stack array a and b Horizontally

In [38]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([9,8,7,6,5,4,3,2,1,])
print(b)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [43]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

How to concatenate array a and b

In [44]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([9,8,7,6,5,4,3,2,1,])
print(b)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [46]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

Create the following pattern without hardcoding .use only numpy function in the below input array a


In [58]:
#array(1,1,1,2,2,2,3,3,3,1,2,3,1,2,3)
a=np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Get The Commons items in a and b array

In [68]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([3,6,7,6,5,8,0,2,1,])
print(b)

[1 2 3 4 5 6 7 8 9]
[3 6 7 6 5 8 0 2 1]


In [69]:
np.intersect1d(a,b)

array([1, 2, 3, 5, 6, 7, 8])

Remove common array from a and b

In [70]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.array([3,6,7,6,5,8,0,2,1,])
print(b)

[1 2 3 4 5 6 7 8 9]
[3 6 7 6 5 8 0 2 1]


In [71]:
np.setdiff1d(a,b)

array([4, 9])

Get The position where a,b element match

In [72]:
a=np.array([1,4,5,6,9,7,6])
b=np.array([1,4,6,4,9,5,6])

print(a)
print(b)

[1 4 5 6 9 7 6]
[1 4 6 4 9 5 6]


In [73]:
np.where(a==b)

(array([0, 1, 4, 6], dtype=int64),)

Get all items between 5-10 from array

In [86]:
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [87]:
np.where((a>=5)&(a<=10))


(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

Swap column 1 and 2 from the array

In [91]:
a=np.arange(1,10).reshape(3,3)
a
a[:,[1,2]]

array([[2, 3],
       [5, 6],
       [8, 9]])

Swap row 1 and 2 in the array

In [96]:
a=np.arange(1,10).reshape(3,3)
a
a[[1,2],:]

array([[4, 5, 6],
       [7, 8, 9]])

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Reverse The Row OF a The 2d array

In [98]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Reverse the column of 2d array

In [100]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
a[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

Create a 2d array of shape 5X3 contain random decimel number between 5 and 10

In [104]:
a=np.random.randint(5,10,15).reshape(5,3)

In [105]:
a


array([[8, 9, 8],
       [8, 9, 7],
       [6, 8, 6],
       [6, 7, 8],
       [5, 8, 5]])

In [108]:
b=np.random.uniform(5,10,size=[5,3])

In [109]:
b

array([[5.0180775 , 9.94994394, 6.27660806],
       [5.3546037 , 8.73796169, 7.53688991],
       [5.84630089, 8.30265376, 8.22915082],
       [9.20072301, 8.6644252 , 6.86298441],
       [6.2690177 , 8.51232493, 7.46664935]])

In [ ]:
#Student of DataScience
#Student of DataTrained-Saurav
#Date-22-Julu-2022
#Time-20:45
