In [1]:
#Import numpy library

In [2]:
import numpy as np

In [3]:
#Create an Array using array function

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
#Create an Array containing numbers from 20 to 40

In [12]:
a1=np.arange(20,41)
a1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [13]:
#Create an array which contain 10 elements and every element is 5

In [15]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
#create a 1-d array and then convert it into 3-d array

In [25]:
a=np.random.randint(10,50,24).reshape(2,3,4)
a



array([[[37, 15, 42, 42],
        [11, 16, 47, 30],
        [24, 22, 17, 13]],

       [[33, 47, 14, 34],
        [25, 16, 26, 29],
        [46, 33, 21, 48]]])

In [26]:
#Create 2-d array which contains random 25 numbers between 0 and 1

In [27]:
z=np.random.randn(25)
z

array([ 1.12621966, -1.4108904 , -1.43327391,  1.50131177, -1.59592736,
        0.75791071,  0.33077389, -1.17799525, -0.68602174,  1.37498643,
        1.19255356, -0.63699975, -0.17327378, -0.85262162, -1.10431167,
       -0.77425963,  0.98311394, -0.87845668, -1.08693695, -0.18097969,
        1.24500117,  0.95316712, -0.95229773, -0.95272653,  0.17579142])

In [28]:
#create array containing 20 random integer then replace every even number with -1

In [36]:
a=np.random.randint(20,100,20)
a[a%2==0]=-1
a


array([21, -1, -1, -1, -1, 65, -1, -1, -1, -1, 23, -1, 79, -1, -1, -1, -1,
       -1, 21, 65])

In [37]:
#You have a matrix
#[[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]]

#Extract [30,35,40] [55, 60, 65]

In [38]:
a=np.array([[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])

In [39]:
a

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [42]:
a[1:3,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

In [43]:
#Concatenate two 1-d array

In [49]:
a=np.array([2,3,4])
b=np.array([3,6,2])
np.hstack((a,b))

array([2, 3, 4, 3, 6, 2])

In [50]:
#vStack 2-d matrix horizontally and vertically

In [64]:
matrix1=np.random.randint(1,10,9).reshape(3,3)
matrix2=np.random.randint(10,20,9).reshape(3,3)

np.vstack((matrix1,matrix2))

array([[ 1,  9,  8],
       [ 1,  1,  2],
       [ 9,  7,  3],
       [11, 17, 17],
       [14, 18, 11],
       [16, 15, 18]])

In [65]:
#3 deimensional array

In [80]:
a=np.array([[[1,2,3],[2,6,4],[3,8,9],[4,7,8],[5,8,7]]])

In [81]:
a

array([[[1, 2, 3],
        [2, 6, 4],
        [3, 8, 9],
        [4, 7, 8],
        [5, 8, 7]]])

In [78]:
a.ndim

3

In [ ]:
#Student of Data Science
#Student of DataTrained- Saurav
#Data-19-July-2022
#Time-23:04