In [ ]:
#Project Numpy 1

In [95]:
import numpy as np

In [107]:
data=np.loadtxt("even_numbers.txt")



In [97]:
data

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.],
       [42., 44., 46., 48., 50.]])

In [98]:
#Check of the type of data

In [100]:
type(data)

numpy.ndarray

In [101]:
#check dtype

In [102]:
data.dtype

dtype('float64')

In [103]:
#chage float to int

In [109]:
data=np.loadtxt("even_numbers.txt",dtype=int)

print(data)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [113]:
#We dont want to to take 1 row  .

In [111]:
data=np.loadtxt("even_numbers.txt",dtype=int,skiprows=True)

In [112]:
data

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [114]:
#we want to use only selected column as per use

In [115]:
data=np.loadtxt("even_numbers.txt",dtype=int,usecols=(1,3))

In [116]:
data

array([[ 4,  8],
       [14, 18],
       [24, 28],
       [34, 38],
       [44, 48]])

In [118]:
#when we want only first column  and show in row from

In [123]:
data=np.loadtxt("even_numbers.txt",dtype=int,usecols=0)

In [124]:
data

array([ 2, 12, 22, 32, 42])

In [125]:
#when we want in string 

In [126]:
data=np.loadtxt("even_numbers.txt",dtype=str,usecols=0)

In [127]:
data

array(['2', '12', '22', '32', '42'], dtype='<U2')

In [128]:
#use another file

In [131]:
data=np.loadtxt("glass.csv",delimiter=",")

In [132]:
data

array([[  1.     ,   1.52101,  13.64   , ...,   0.     ,   0.     ,
          1.     ],
       [  2.     ,   1.51761,  13.89   , ...,   0.     ,   0.     ,
          1.     ],
       [  3.     ,   1.51618,  13.53   , ...,   0.     ,   0.     ,
          1.     ],
       ...,
       [212.     ,   1.52065,  14.36   , ...,   1.64   ,   0.     ,
          7.     ],
       [213.     ,   1.51651,  14.38   , ...,   1.57   ,   0.     ,
          7.     ],
       [214.     ,   1.51711,  14.23   , ...,   1.67   ,   0.     ,
          7.     ]])

In [133]:
##check shape 

In [134]:
data.shape

(214, 11)

In [135]:
#data type

In [136]:
data.dtype

dtype('float64')

In [138]:
#when we want to remove 1st row which are index value

In [137]:
data[:,1]

array([1.52101, 1.51761, 1.51618, 1.51766, 1.51742, 1.51596, 1.51743,
       1.51756, 1.51918, 1.51755, 1.51571, 1.51763, 1.51589, 1.51748,
       1.51763, 1.51761, 1.51784, 1.52196, 1.51911, 1.51735, 1.5175 ,
       1.51966, 1.51736, 1.51751, 1.5172 , 1.51764, 1.51793, 1.51721,
       1.51768, 1.51784, 1.51768, 1.51747, 1.51775, 1.51753, 1.51783,
       1.51567, 1.51909, 1.51797, 1.52213, 1.52213, 1.51793, 1.51755,
       1.51779, 1.5221 , 1.51786, 1.519  , 1.51869, 1.52667, 1.52223,
       1.51898, 1.5232 , 1.51926, 1.51808, 1.51837, 1.51778, 1.51769,
       1.51215, 1.51824, 1.51754, 1.51754, 1.51905, 1.51977, 1.52172,
       1.52227, 1.52172, 1.52099, 1.52152, 1.52152, 1.52152, 1.523  ,
       1.51574, 1.51848, 1.51593, 1.51631, 1.51596, 1.5159 , 1.51645,
       1.51627, 1.51613, 1.5159 , 1.51592, 1.51593, 1.51646, 1.51594,
       1.51409, 1.51625, 1.51569, 1.51645, 1.51618, 1.5164 , 1.51841,
       1.51605, 1.51588, 1.5159 , 1.51629, 1.5186 , 1.51841, 1.51743,
       1.51689, 1.51

In [139]:
#use genfromtxt- ? what is genfromtxt ?
# when we have a data but in data there are nan value . if in any dataset nan value available then we use genfromtxt

In [142]:
data=np.genfromtxt("odd_numbers.csv",delimiter=",")

In [143]:
data

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [43., 45., 47., 49., nan]])

In [144]:
#see  in right corner there is one value nan. then how to fill the nan value

In [151]:
data=np.genfromtxt("odd_numbers.csv",delimiter=",",filling_values=1,invalid_raise=True)

In [149]:
data

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [43., 45., 47., 49.,  1.]])

In [152]:
#when we have a question mark in dataset. lets se how we handle

In [156]:
data=np.genfromtxt("odd_numbers.csv",delimiter=",",missing_values='?',filling_values=0,invalid_raise=True)

In [157]:
data

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [43., 45., 47., 49.,  0.]])

In [158]:
#now i want in the place of zero i want to put 'Unknown'

In [161]:
#now open another file which have types of data

In [169]:
data=np.genfromtxt('highway.csv',delimiter=",",dtype=str,missing_values='?',filling_values=0)
data

array([['E1', 'M', '3', ..., 'SHORT', 'S', 'WOOD'],
       ['E2', 'A', '25', ..., 'SHORT', 'S', 'WOOD'],
       ['E3', 'A', '39', ..., '?', 'S', 'WOOD'],
       ...,
       ['E90', 'M', '7', ..., 'LONG', 'F', 'ARCH'],
       ['E100', 'O', '43', ..., '?', 'F', '?'],
       ['E109', 'A', '28', ..., '?', 'F', '?']], dtype='<U8')

In [170]:
#now i want in the place of '?' i want to put 'Unknown'

In [171]:
data[data=='?']='Unknown'

In [172]:
data

array([['E1', 'M', '3', ..., 'SHORT', 'S', 'WOOD'],
       ['E2', 'A', '25', ..., 'SHORT', 'S', 'WOOD'],
       ['E3', 'A', '39', ..., 'Unknown', 'S', 'WOOD'],
       ...,
       ['E90', 'M', '7', ..., 'LONG', 'F', 'ARCH'],
       ['E100', 'O', '43', ..., 'Unknown', 'F', 'Unknown'],
       ['E109', 'A', '28', ..., 'Unknown', 'F', 'Unknown']], dtype='<U8')

In [178]:
#if we want to find how much M available in our data set which are available on or data set

In [174]:
data=data[:,1]

In [175]:
data

array(['M', 'A', 'A', 'A', 'M', 'A', 'A', 'M', 'A', 'A', 'A', 'M', 'A',
       'A', 'A', 'M', 'A', 'A', 'A', 'M', 'M', 'A', 'O', 'M', 'A', 'M',
       'A', 'A', 'M', 'A', 'M', 'O', 'M', 'O', 'A', 'M', 'M', 'A', 'A',
       'M', 'M', 'M', 'O', 'M', 'A', 'M', 'M', 'A', 'A', 'M', 'A', 'M',
       'A', 'M', 'M', 'M', 'A', 'M', 'Y', 'M', 'A', 'O', 'O', 'A', 'M',
       'O', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'O', 'A', 'M', 'M',
       'A', 'M', 'A', 'M', 'O', 'O', 'M', 'M', 'A', 'A', 'A', 'A', 'O',
       'Y', 'Y', 'M', 'M', 'M', 'M', 'A', 'O', 'O', 'M', 'A', 'M', 'A',
       'O', 'M', 'O', 'A'], dtype='<U8')

In [177]:
m=0
for i in data:
    if i=='M':
        
        m+=1
print(m)

41


In [ ]:
#Student of Data Science
#Studen of DataTrained-Saurav
#Data-20-07-2022
#Time-13:50